# Copyright 2022-2025 TII (SSRC) and the Ghaf contributors
# SPDX-License-Identifier: Apache-2.0

[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "usb_passthrough_manager"
version = "0.1.0"
description = "Host ↔ guest VM with real user, USB passthrough management over vsock with a GTK4 (PyGObject) UI"
authors = [{ name = "Ganga Ram" }]
readme = "README.md"
requires-python = ">=3.13"
license = "Apache-2.0"
dependencies = [
  "PyGObject>=3.46",
]

# Ignore formatting error "E402 Module level import not at top of file"
# Ordering is required to select gtk version
[tool.ruff]
ignore = ["E402"]

# Optional extras (keep or remove as you like)
[project.optional-dependencies]
dev = ["pytest", "ruff", "mypy"]

# GUI launcher for the app window; service binaries stay as console scripts.
[project.gui-scripts]
upm_app = "bin.upm_app:main"

[project.scripts]
upm_service = "bin.upm_service:main"
upm_host_service = "bin.upm_host:main"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.data-files]
"share/upm/icon" = ["assets/icon/usb.png"]
